name: Linting and Type Checking

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      
      
      # use uv package manager
      - name: Install uv
        run: pip install uv
      - uses: actions/cache@v4
        name: Cache dependencies
        with:
          path: ~/.cache/uv
          key: uv-${{ hashFiles('pyproject.toml') }}
      - name: Install dependencies
        run: |
          uv venv
          uv pip install -e ".[dev]"
      - name: Lint
        run: uv run poe lint
      - name: Type Check
        run: uv run poe type-check